export const ResourceMessage: any = {
    "Hallway": "门厅",
    "LivingRoom": "客厅",
    "DiningRoom": "餐厅",
    "LivingDiningRoom": "客餐厅",
    "Balcony": "阳台",
    "Kitchen": "厨房",
    "Bathroom": "卫生间",
    "MasterBathroom": "主卫",
    "SecondBathroom": "次卫",
    "Bedroom": "卧室",
    "MasterBedroom": "主卧",
    "SecondBedroom": "次卧",
    "KidsRoom": "儿童房",
    "ElderlyRoom": "老人房",
    "Library": "书房",
    "CloakRoom": "衣帽间",
    "StorageRoom": "存储间",
    "NannyRoom": "保姆间",
    "LaundryRoom": "洗衣房",
    "Lounge": "休息室",
    "Auditorium": "影视厅",
    "Stairwell": "楼梯间",
    "Aisle": "过道",
    "Corridor": "走廊",
    "Office": "办公间",
    "Outdoors": "庭院",
    "EntranceHallway": "入口走廊",
    "ProductShowcase": "产品展示区",
    "Studio": "工作室",
    "Basement": "地下室",
    "HomeCinema": "家庭影院",
    "Den": "窝",
    "PorchBalcony": "门廊阳台",
    "EquipmentRoom": "设备间",
    "Courtyard": "庭院",
    "Garage": "车库",
    "Terrace": "阳台",
    "OtherRoom": "其它",
    "None": "未定义",
    "none": "未定义",
    "roomNumber": "房间数目",
    "totalArea": "总面积",
    "doorNumber": "门数目",
    "windowNumber": "窗数目",
    "checkDesignFile": "检测文件",
    "checkRoomName": "检测房间名信息",
    "checkProductID": "检测产品ID信息",
    "checkEntryDoor": "检测入户门信息",
    "checkPano": "检测全景图信息",
    "checkHousePlan": "检测户型图信息",
    "checkOutdoor": "检测室外图信息",
    "downloadError": "导出错误信息",
    "noExtensionInfo": "无扩展信息",
    "noEntryDoorInfo": "无入户门信息",
    "noInteriorDoorInfo": "无室内门信息",
    "noEntryDoorAndInteriorDoorInfo": "无入户门和室内门信息",
    "noDoorInfo": "没有门信息",
    "noOutDoorInfo": "无室外场景信息",
    "noPanoInfo": "无全景图信息",
    "noMiniMapInfo": "无小地图信息",
    "openAllLights": "打开所有光源",
    "closeAllLights": "关闭所有光源",
    "addPointLight": "添加点光源",
    "resetLight": "重置",
    "3Dset": "3D设置",
    "camera": "相机",
    "snapShot": "视角快照",
    "lightSource": "光源",
    "noramlPerspective": "正常透视",
    "orthographicOverlook": "正交俯视",
    "angle": "角度",
    "frustum": "视锥",
    "renderSingle": "显示物品",
    "renderAll": "显示全部",
    "renderFurniture": "渲染物品",
    "renderFlipx": "水平翻转",
    "renderFlipz": "前后翻转",
    "return": "返回"
}

export const RoomTypeArray: Array<string> = [
    "Hallway",
    "LivingRoom",
    "DiningRoom",
    "LivingDiningRoom",
    "Balcony",
    "Kitchen",
    "Bathroom",
    "MasterBathroom",
    "SecondBathroom",
    "Bedroom",
    "MasterBedroom",
    "SecondBedroom",
    "KidsRoom",
    "ElderlyRoom",
    "Library",
    "CloakRoom",
    "StorageRoom",
    "NannyRoom",
    "LaundryRoom",
    "Lounge",
    "Auditorium",
    "Stairwell",
    "Aisle",
    "Corridor",
    "Office",
    "Outdoors",
    "EntranceHallway",
    "ProductShowcase",
    "Studio",
    "Basement",
    "HomeCinema",
    "Den",
    "PorchBalcony",
    "EquipmentRoom",
    "Courtyard",
    "Garage",
    "Terrace",
    "OtherRoom",
    "None",
    "none",
];

export enum RenderMode {
    AllRender,
    SingleRender
}